name = "my-bot"
main = "src/index.js"
compatibility_date = "2024-10-02"

[vars]
TELEGRAM_BOT_TOKEN = "8679743132:AAEntzXsHdX6cV8MMUdtcL_u5iORdjd-g9s"

# اتصال به دیتابیس داخلی کلودفلر برای حافظه ربات
[[d1_databases]]
binding = "DB"
database_name = "bot-database"
database_id = "your-database-id-placeholder"
